Repository sw20-tug/ASD-Morning-7, pull requests merged in 2020-04, with the labels that each got.

#29 COOK-001C implemented CRUD and created recipe model [GP, PD, KS, ZD]
  server/src/main/java/at/tugraz/asdmorning7/cook/CookApplication.java
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/main/java/at/tugraz/asdmorning7/cook/exceptions/RecipeNotFoundException.java
  server/src/main/java/at/tugraz/asdmorning7/cook/models/Recipe.java
  server/src/main/java/at/tugraz/asdmorning7/cook/repositories/RepositoryHandler.java
  server/src/main/resources/application.properties
Labels: back-end

#33 COOK-001C Unify coding standard, rename methods [KS, PD]
  server/src/main/java/at/tugraz/asdmorning7/cook/CookApplication.java
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipesController.java
  server/src/main/java/at/tugraz/asdmorning7/cook/exceptions/RecipeNotFoundException.java
  server/src/main/java/at/tugraz/asdmorning7/cook/models/Recipe.java
  server/src/main/java/at/tugraz/asdmorning7/cook/repositories/RecipesRepository.java
Labels: back-end

#35 COOK-002A started to implement form , actions and reducer for adding new recipes [PS, RT]
  client/package-lock.json
  client/package.json
  client/src/modules/app/App.js
  client/src/modules/app/appActions.js
  client/src/modules/app/appReducer.js
  client/src/modules/app/components/AddRecipeDialog/AddRecipeDialog.js
  client/src/modules/app/components/AddRecipeDialog/ThumbnailUploader.js
  client/src/modules/app/components/Navigation.js
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
  client/src/modules/recipesOverview/RecipesOverview.js
  client/src/reducers.js
Labels: front-end

#36 COOK-002A extended new recipe form [PS, RT]
  client/src/modules/app/components/AddRecipeDialog/AddRecipeDialog.js
  client/src/modules/app/components/AddRecipeDialog/Step.js
  client/src/modules/app/components/AddRecipeDialog/ThumbnailUploader.js
Labels: front-end

#34 COOK-001D Recipe overview: Back end Testing [KS, GP, PD, ZD]
  .github/workflows/maven.yml
  .gitignore
  README.md
  server/.gitignore
  server/pom.xml
  server/src/test/java/at/tugraz/asdmorning7/cook/CookApplicationTests.java
  server/src/test/java/at/tugraz/asdmorning7/cook/controllers/integration/RecipesControllerTests.java
  server/src/test/java/at/tugraz/asdmorning7/cook/controllers/unit/RecipesControllerUnitTest.java
Labels: back-end, testing

#38 COOK-002A fixed bugs in add new recipe feature [PS, RT]
  client/src/modules/app/components/AddRecipeDialog/AddRecipeDialog.js
  client/src/modules/app/components/AddRecipeDialog/Step.js
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipesOverview/components/RecipesList.js
Labels: front-end

#41 COOK-Hotfix Add merge hook for GitHub Actions [KS]
  .github/workflows/maven.yml
Labels: back-end

#42 COOK-Hotfix Fix GitHub Actions configuration [PD]
  .github/workflows/maven.yml
Labels: testing

#43 COOk-Hotfix Fix spelling mistake in README [PD]
  README.md
Labels: documentation

#44 COOK-Hotfix Fix CORS error [PD]
  client/src/modules/app/components/AddRecipeDialog/AddRecipeDialog.js
  client/src/modules/recipes/recipesActions.js
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/StepController.java
Labels: back-end, front-end
