Repository sw20-tug/ASD-Morning-7, pull requests merged in 2020-05, with the labels that each got.

#51 COOK_001 Added picture supporting the recipe name in recipe overview table [PS]
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
  client/src/modules/recipesOverview/components/RecipesList.js
Labels: front-end

#54 COOK_001 fixed bug that caused a recipe showing up twice after creating it [PS]
  client/src/modules/recipes/recipesActions.js
Labels: front-end

#55 Feature/COOK_002C first testcases [BC, KS, PS, RT]
  client/package.json
  client/src/modules/app/components/navigation.test.js
  client/src/modules/recipesOverview/components/overview.test.js
Labels: testing

#56 COOK_002D JUnit tests - add/find recipe [GP, ZD]
  server/src/test/java/at/tugraz/asdmorning7/cook/unit/RecipesControllerUnitTest.java
Labels: back-end, testing

#58 COOK-004B Rename recipes: Back end
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/test/java/at/tugraz/asdmorning7/cook/integration/RecipeControllerTests.java
  server/src/test/java/at/tugraz/asdmorning7/cook/integration/StepControllerTests.java
  server/src/test/java/at/tugraz/asdmorning7/cook/unit/RecipeControllerUnitTests.java
Labels: back-end

#57 COOK_004A Implemented feature for inline editing recipe names in recipe overview - also implemented a test [KS, PS, ZD]
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/modules/app/components/navigation.test.js
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
  client/src/modules/recipesOverview/RecipesOverview.js
  client/src/modules/recipesOverview/components/RecipesList.js
  client/src/modules/recipesOverview/components/RecipesListRow.js
  client/src/modules/recipesOverview/components/overview.test.js
Labels: front-end

#61 COOK-Hotfix Added ingredients attribute [BC, MF, PD]
  server/src/main/java/at/tugraz/asdmorning7/cook/models/Recipe.java
  server/src/test/java/at/tugraz/asdmorning7/cook/unit/RecipeControllerUnitTests.java
Labels: back-end, bug

#64 COOK-009B Implement edit recipe [BC, MF, PD, RT]
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/test/java/at/tugraz/asdmorning7/cook/unit/RecipeControllerUnitTests.java
Labels: back-end

#63 COOK-009A Implemented feature to edit recipes (also implemented a context menu for mutating recipes) [GP, KS, PS, ZD]
  client/src/modules/app/App.js
  client/src/modules/app/components/AddRecipeDialog/AddRecipeDialog.js
  client/src/modules/app/components/Navigation.js
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
  client/src/modules/recipesOverview/RecipesOverview.js
  client/src/modules/recipesOverview/components/RecipesList.js
  client/src/modules/recipesOverview/components/RecipesListRow.js
  client/src/modules/recipesOverview/components/overview.test.js
Labels: front-end

#65 COOK-005A Implemented feature to delete recipes [GP, KS, PS, ZD]
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
  client/src/modules/recipesOverview/RecipesOverview.js
  client/src/modules/recipesOverview/components/RecipesList.js
  client/src/modules/recipesOverview/components/RecipesListRow.js
Labels: front-end

#66 COOK-012 Add yml file for npm CI [KS, MF]
  .github/workflows/nodejs.yml
Labels: front-end, sp:2, testing

#67 COOK-004A Fix recipe rename bug [PD, PS]
  client/src/modules/recipes/recipesActions.js
Labels: front-end

#68 COOK-009A general bug fixing in edit recipe feature (ingredients and steps) [PS]
  client/src/modules/app/components/Navigation.js
  client/src/modules/app/components/RecipeDialog/RecipeDialog.js
  client/src/modules/app/components/RecipeDialog/Step.js
  client/src/modules/app/components/RecipeDialog/ThumbnailUploader.js
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
Labels: front-end

#69 COOK_007 add search through all recipes [GP, KS, PS, ZD]
  client/src/modules/app/App.js
  client/src/modules/recipes/recipesActions.js
  client/src/modules/recipes/recipesReducer.js
  client/src/modules/recipesOverview/RecipesOverview.js
Labels: front-end

#70 COOK-009B bug fix steps [BC, MF, PD, RT]
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/test/java/at/tugraz/asdmorning7/cook/unit/RecipeControllerUnitTests.java
Labels: back-end, bug
