Repository sw20-tug/ASD-Morning-7, pull requests merged in 2020-06, with the labels that each got.

#74 COOK_014 Bugfix: Steps are now sorted on the server [GP, RT]
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/main/java/at/tugraz/asdmorning7/cook/models/Recipe.java
Labels: back-end, bug

#75 COOK-006 implemented feature to filter recipes [BC, PS, ZD]
  client/src/modules/app/App.js
  client/src/modules/app/components/Navigation.js
  client/src/modules/app/components/RecipeDialog/RecipeDialog.js
  client/src/modules/app/components/RecipeDialog/Step.js
  client/src/modules/app/components/RecipeDialog/ThumbnailUploader.js
  client/src/modules/app/components/navigation.test.js
  client/src/modules/recipesOverview/RecipesOverview.js
  client/src/modules/recipesOverview/components/RecipesList.js
  client/src/modules/recipesOverview/components/RecipesListRow.js
  client/src/modules/recipesOverview/components/overview.test.js
  client/template/index.html
Labels: front-end

#72 COOK-013 Bundle client and server applications [MF, PD]
  client/src/modules/app/components/RecipeDialog/RecipeDialog.js
  client/src/modules/recipes/recipesActions.js
  server/src/main/java/at/tugraz/asdmorning7/cook/controllers/RecipeController.java
  server/src/main/java/at/tugraz/asdmorning7/cook/models/Recipe.java
  server/src/main/resources/static/index.html
Labels: enhancement

#78 COOK-003 Fixed caching bug when adding and editing recipes and a bug that prevented focusing the inline name editing field by opening the detail view dialog [PS]
  client/src/modules/app/App.js
  client/src/modules/app/components/Navigation.js
  client/src/modules/app/components/RecipeDialog/RecipeDialog.js
  client/src/modules/recipesOverview/components/RecipesListRow.js
  server/src/main/resources/static/index.html
Labels: bug, front-end

#79 COOK-008 Fixed bug where button to add steps and functions to set thumbnails were still showing up in detail view [PS]
  client/package-lock.json
  client/src/modules/app/components/RecipeDialog/RecipeDialog.js
  client/src/modules/app/components/RecipeDialog/ThumbnailUploader.js
  server/src/main/resources/static/index.html
Labels: bug, front-end
